// atlas-0 S4 spike, fix round 1, item 2 — the ".prj ignored" seeded fault, on the PARSER side
// this time (correctness.spec.ts's seeded-fault run already covers the EXPECTATION side: a ground
// truth deliberately left in raw metres). `utm_zone_noprj.zip` is the SAME shapefile as
// utm_zone.zip (same .shp/.shx/.dbf bytes), generated by the same fixtures/generate_fixtures.R,
// with only its .prj component dropped before zipping — a real file a reader could actually be
// handed, not a hand-edited expectation.
//
// `test.fail()`: this test's assertion (parsed coords match the true WGS84 reprojection) is
// EXPECTED to fail, because there is no CRS in the zip for shpjs to reproject with. Playwright
// reports an expected failure as a pass (exit 0) — so a green run here is the proof that a dropped
// .prj is still caught. If this ever unexpectedly PASSES (exit 1, "unexpected pass"), that would
// itself be a finding: it would mean shpjs somehow produced WGS84-range coordinates without any
// CRS input, which would need investigating, not silently accepting.
import { test, expect } from "@playwright/test";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const manifest = JSON.parse(readFileSync(path.join(here, "..", "fixtures", "fixtures_manifest.json"), "utf8"));

test.fail();

test("utm_zone_noprj via shpjs: no .prj in the zip -> must NOT match the true WGS84 reprojection", async ({
  page,
}) => {
  const consoleMessages: string[] = [];
  page.on("console", (msg) => consoleMessages.push(`[${msg.type()}] ${msg.text()}`));
  page.on("pageerror", (err) => consoleMessages.push(`[pageerror] ${err.message}`));

  await page.goto("/");
  await page.waitForFunction(() => (window as any).__spike4 !== undefined);

  const r = await page.evaluate((url) => (window as any).__spike4.parseShp(url), "/utm_zone_noprj.zip");

  // recorded regardless of pass/fail below — this is the actual finding atlas-6 needs: does shpjs
  // error, warn, or silently hand back raw metres when a shapefile has no .prj?
  console.log("utm_zone_noprj/shpjs result:", JSON.stringify(r));
  console.log("utm_zone_noprj/shpjs browser console during parse:", JSON.stringify(consoleMessages));

  const m = manifest.utm_zone_noprj;
  expect(r.vertexCount, "utm_zone_noprj vertexCount").toBe(m.vertex_count);

  // the assertion under test.fail(): SHOULD fail, because there is no .prj to reproject with.
  const truth = m.wgs84_ground_truth_bbox;
  for (let i = 0; i < 4; i++) {
    expect(
      Math.abs(r.bbox[i] - truth[i]),
      `utm_zone_noprj bbox[${i}] got ${r.bbox[i]} vs true WGS84 ${truth[i]}`,
    ).toBeLessThan(1e-6);
  }
});
