// atlas-0 S4 spike, fix round 3 (reviewer finding N2) — the ".prj ignored" seeded fault, on the
// PARSER side (correctness.spec.ts's seeded-fault run already covers the EXPECTATION side: a
// ground truth deliberately left in raw metres). `utm_zone_noprj.zip` is the SAME shapefile as
// utm_zone.zip (same .shp/.shx/.dbf bytes), generated by the same fixtures/generate_fixtures.R,
// with only its .prj component dropped before zipping — a real file a reader could actually be
// handed, not a hand-edited expectation.
//
// N2 (reviewer): a blanket `test.fail()` used to wrap this test's whole body. `test.fail()`
// accepts ANY failure — a missing fixture, a parser exception, a server that never started would
// all report the same green "expected failure" and "a dropped .prj is still caught" would be
// unproven. Fixed: an ORDINARY test that asserts the actual trigger and actual symptom positively
// (below), so only those specific, expected outcomes are accepted — any other failure (fixture
// missing, parse exception, unexpected .prj) makes the test genuinely FAIL, not pass for the
// wrong reason. See RESULTS.md for the two seeded-fault runs proving this (a .prj put back, and
// the fixture file renamed away — both turn this test red where the old `test.fail()` version
// would have stayed green).
import { test, expect } from "@playwright/test";
import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const manifest = JSON.parse(readFileSync(path.join(here, "..", "fixtures", "fixtures_manifest.json"), "utf8"));
const FIXTURE_ZIP = path.join(here, "..", "fixtures", "utm_zone_noprj.zip");
const METRES_PER_DEG = 111_320; // same conversion correctness.spec.ts uses for its utm_zone reprojection-error number

test("utm_zone_noprj: the zip really has no .prj, and shpjs silently returns raw UTM metres, far from the true WGS84 position", async ({
  page,
}) => {
  // (1) positive proof of the TRIGGER: the fixture file on disk has no .prj entry. Reading the
  // actual archive's entry list (not asking the parser what it did) is what makes this fail
  // loudly — not silently pass as "expected" — if the fixture is missing, renamed, or (seeded
  // fault) accidentally has its .prj restored: `execFileSync` throws if `unzip` can't find the
  // file at all, and the `.prj` assertion below fails explicitly if one is present.
  const entries = execFileSync("unzip", ["-Z1", FIXTURE_ZIP], { encoding: "utf8" }).trim().split("\n");
  expect(entries.some((e) => e.toLowerCase().endsWith(".shp")), `zip entries: ${JSON.stringify(entries)}`).toBe(true);
  expect(
    entries.some((e) => e.toLowerCase().endsWith(".prj")),
    `zip entries: ${JSON.stringify(entries)} — a .prj is present, this fixture is supposed to have none`,
  ).toBe(false);

  const consoleMessages: string[] = [];
  page.on("console", (msg) => consoleMessages.push(`[${msg.type()}] ${msg.text()}`));
  page.on("pageerror", (err) => consoleMessages.push(`[pageerror] ${err.message}`));

  await page.goto("/");
  await page.waitForFunction(() => (window as any).__spike4 !== undefined);

  // no try/catch here on purpose: a parser exception (or a 404 because the fixture file is
  // missing) must reject this evaluate() call and fail the test, not be swallowed into a "the
  // test failed, therefore the fault is proven" result the way the old test.fail() did.
  const r = await page.evaluate((url) => (window as any).__spike4.parseShp(url), "/utm_zone_noprj.zip");

  console.log("utm_zone_noprj/shpjs result:", JSON.stringify(r));
  console.log("utm_zone_noprj/shpjs browser console during parse:", JSON.stringify(consoleMessages));

  const m = manifest.utm_zone_noprj;
  expect(r.vertexCount, "utm_zone_noprj vertexCount").toBe(m.vertex_count);

  // (2) positive proof of the SYMPTOM: shpjs returned the fixture's raw UTM EASTING/NORTHING
  // range, not "some value that happens not to equal the WGS84 truth" (a much weaker, purely
  // negative claim a lot of unrelated bugs could also satisfy).
  const [utmXmin, utmYmin, utmXmax, utmYmax] = m.bbox_utm_metres;
  const TOL_M = 1; // fixture corners are exact integers in metres; 1 m covers any float noise
  expect(r.bbox[0], `easting min ${r.bbox[0]} in UTM range [${utmXmin}, ${utmXmax}]`).toBeGreaterThanOrEqual(utmXmin - TOL_M);
  expect(r.bbox[0], `easting min ${r.bbox[0]} in UTM range [${utmXmin}, ${utmXmax}]`).toBeLessThanOrEqual(utmXmax + TOL_M);
  expect(r.bbox[2], `easting max ${r.bbox[2]} in UTM range [${utmXmin}, ${utmXmax}]`).toBeGreaterThanOrEqual(utmXmin - TOL_M);
  expect(r.bbox[2], `easting max ${r.bbox[2]} in UTM range [${utmXmin}, ${utmXmax}]`).toBeLessThanOrEqual(utmXmax + TOL_M);
  expect(r.bbox[1], `northing min ${r.bbox[1]} in UTM range [${utmYmin}, ${utmYmax}]`).toBeGreaterThanOrEqual(utmYmin - TOL_M);
  expect(r.bbox[1], `northing min ${r.bbox[1]} in UTM range [${utmYmin}, ${utmYmax}]`).toBeLessThanOrEqual(utmYmax + TOL_M);
  expect(r.bbox[3], `northing max ${r.bbox[3]} in UTM range [${utmYmin}, ${utmYmax}]`).toBeGreaterThanOrEqual(utmYmin - TOL_M);
  expect(r.bbox[3], `northing max ${r.bbox[3]} in UTM range [${utmYmin}, ${utmYmax}]`).toBeLessThanOrEqual(utmYmax + TOL_M);
  // and nowhere near a valid lon/lat, the "these are obviously metres, not degrees" signal
  expect(Math.abs(r.bbox[0]), `|easting|=${Math.abs(r.bbox[0])} is nowhere near a valid longitude`).toBeGreaterThan(180);
  expect(Math.abs(r.bbox[1]), `|northing|=${Math.abs(r.bbox[1])} is nowhere near a valid latitude`).toBeGreaterThan(90);

  // (3) positive proof of "silently" — atlas-6 needs this asserted, not just logged: no
  // console.warn/error, no thrown pageerror, during the parse.
  expect(consoleMessages, `expected no console output, got: ${JSON.stringify(consoleMessages)}`).toHaveLength(0);

  // (4) positive proof the WGS84 comparison error is not a near-miss but a metres/degrees-scale
  // confusion — same delta*METRES_PER_DEG convention correctness.spec.ts's utm_zone/shpjs
  // reprojection-error check uses, so the two numbers are directly comparable.
  const truth = m.wgs84_ground_truth_bbox;
  const errMetres =
    Math.max(
      Math.abs(r.bbox[0] - truth[0]),
      Math.abs(r.bbox[1] - truth[1]),
      Math.abs(r.bbox[2] - truth[2]),
      Math.abs(r.bbox[3] - truth[3]),
    ) * METRES_PER_DEG;
  expect(errMetres, `WGS84 comparison error should be > 1e6 m, got ${errMetres.toFixed(1)} m`).toBeGreaterThan(1e6);
});
