import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { expect, test, type Page } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import pdfParse from "pdf-parse";
import { unzipSync } from "fflate";
import { BUCKET, collectRequests, routeBucket, routeSealFixture, routeSession } from "./hermetic";
import { blockWasm } from "./map-hermetic";
import { normalizePdfText } from "./pdfText";
// `routeVariedBasemapStyle` moved with `gotoReport` into report-hermetic.ts (atlas-8 step 3); it is
// no longer called from this file directly.
import { BOOT_V7, BOOT_V9, gotoReport, PL } from "./report-hermetic";
import { encodePlace, type Place } from "../src/lib/geo/placeCodec";

// atlas-7 steps 2-4, fix round 1: report.html's own hermetic smoke suite. HERMETIC per this
// repo's convention (e2e/hermetic.ts): every bucket URL is `page.route`d to a fixture, never the
// live network.
//
// TWO FIXTURE TIERS. "report.html renders zone places from boot.json" / "D6 access gate" / most of
// "exports"/"accessibility" use `blockWasm()` (species degrades to "No species found for this
// area.", disclosed, not hidden -- a zone place's SCORES need no engine at all). "engine-backed
// paths" and the PDF checks below use REAL DuckDB-WASM against real Parquet fixtures
// (e2e/fixtures/report/*.parquet, generated by generate.sql) for the species table AND a custom
// (drawn) place's scores -- fix round 1, item 2.
//
// The first tier's fixtures (BOOT_V9/BOOT_V7/PL/gotoReport) moved to e2e/report-hermetic.ts in
// atlas-8 step 3, so e2e/matrix.a11y.spec.ts audits the SAME document rather than a near-copy of it.
test.describe("report.html renders zone places from boot.json", () => {
  test("two Program Areas: header, table of scores and per-place flowers all render", async ({
    page,
  }) => {
    await gotoReport(page, { ver: "v9", preview: true });

    await expect(page.locator("h1")).toHaveText("BOEM Marine Sensitivity Report");
    await expect(page.locator(".report-chip")).toHaveText("v9 · prerelease · restricted");

    // the Table of Scores: one row per place, in submission order, Overall = plain mean of the
    // components PRESENT (model.ts's own rule -- GAA: (50+30+40)/3 = 40, ALA: (55+20)/2 = 37.5 -> 38).
    const table = page.locator("table", { hasText: "Mean component and overall scores" });
    const gaaRow = table.locator("tr", { hasText: "Gulf of America" });
    await expect(gaaRow).toContainText("40");
    const alaRow = table.locator("tr", { hasText: "Alaska" });
    await expect(alaRow).toContainText("38");

    // one flower figure per place (tabs on screen; both panels exist in the DOM regardless of
    // which is the active tab -- report.css's [hidden] rule, not a conditional {#if}).
    await expect(page.locator("figure.flower-panel")).toHaveCount(2);

    // species degrades to the documented empty case for this suite's fixtures (see file header).
    await expect(page.getByText("No species found for this area.").first()).toBeVisible();

    await expect(page.locator(".progress-line")).toContainText("Done");
  });

  test("the permalink round-trips ver and pl", async ({ page }) => {
    await gotoReport(page, { ver: "v9", preview: true });
    const link = page.locator(".report-header a");
    await expect(link).toHaveAttribute("href", /ver=v9/);
    await expect(link).toHaveAttribute("href", /pl=/);
  });

  // fix list #13 (SC 4.1.2): the "Plot of Scores" tabs used to be HALF a tab widget -- named
  // correctly, `aria-selected` right, but no `role="tabpanel"`, no `aria-controls`/
  // `aria-labelledby` linking a tab to its figure, and no Arrow-key navigation (each tab was its
  // own Tab stop; a screen reader announced "tab, 1 of 2" and Arrow Right did nothing). Fix:
  // `role="tabpanel"` + `aria-labelledby` on each figure, `aria-controls` + `id` on each tab, and
  // a roving tabindex driven by the SAME `nextRovingIndex` (roving.ts) the tool rail already
  // uses. REVERTED (this fix alone) -> RED: `getByRole("tabpanel")` matches nothing, and
  // ArrowRight leaves both `activeFlower` and focus unchanged.
  test("the flower tabs are a real tab widget: linked panels and Arrow-key navigation", async ({
    page,
  }) => {
    await gotoReport(page, { ver: "v9", preview: true });

    const tablist = page.getByRole("tablist", { name: "Places" });
    const tabs = tablist.getByRole("tab");
    await expect(tabs).toHaveCount(2);
    const firstTab = tabs.first();
    const secondTab = tabs.nth(1);

    // each tab really CONTROLS a linked, existing tabpanel (SC 4.1.2: no aria-controls target may
    // be missing) -- not just named correctly on its own.
    const firstPanelId = await firstTab.getAttribute("aria-controls");
    expect(firstPanelId).toBeTruthy();
    const firstPanel = page.locator(`#${firstPanelId}`);
    await expect(firstPanel).toHaveCount(1);
    await expect(firstPanel).toHaveAttribute("role", "tabpanel");
    const firstPanelLabelledBy = await firstPanel.getAttribute("aria-labelledby");
    expect(firstPanelLabelledBy).toBe(await firstTab.getAttribute("id"));

    // roving tabindex: only the SELECTED tab is a Tab stop; the other is reachable by Arrow only.
    expect(await firstTab.getAttribute("aria-selected")).toBe("true");
    expect(await firstTab.getAttribute("tabindex")).toBe("0");
    expect(await secondTab.getAttribute("tabindex")).toBe("-1");

    await firstTab.focus();
    await page.keyboard.press("ArrowRight");
    await expect(secondTab).toBeFocused();
    expect(await secondTab.getAttribute("aria-selected")).toBe("true");
    expect(await firstTab.getAttribute("aria-selected")).toBe("false");
    // wraps at the end, back to the first tab -- the SAME wrap-around rule the rail uses.
    await page.keyboard.press("ArrowRight");
    await expect(firstTab).toBeFocused();
  });
});

test.describe("D6 access gate + the PREVIEW banner/watermark (plan D6, master plan D6/D9)", () => {
  test("a restricted release on a preview session shows the gold banner and the print watermark", async ({
    page,
  }) => {
    await gotoReport(page, { ver: "v9", preview: true });
    await expect(page.locator(".preview-banner")).toContainText("PREVIEW");
    await expect(page.locator(".print-watermark")).toHaveText("PREVIEW");
  });

  test("a public release shows neither the banner nor the watermark", async ({ page }) => {
    await gotoReport(page, { ver: "v7", preview: false });
    await expect(page.locator(".preview-banner")).toHaveCount(0);
    await expect(page.locator(".print-watermark")).toHaveText("");
  });

  test("a restricted release on the PUBLIC host (no preview session) renders nothing to report on", async ({
    page,
  }) => {
    // v9 is restricted and there is no session -- the same D6 gate index.html's own inline script
    // enforces falls through to latest.txt (v7 here), which was never asked for as a place.
    await blockWasm(page);
    await routeBucket(page, "v7", BOOT_V7);
    await routeSession(page, null);
    await routeSealFixture(page);
    await page.goto(`/report.html?ver=v9#pl=${PL}`);
    // v7's boot has no GAA/ALA-matching report content for a request that named v9 explicitly and
    // was denied -- the document still renders (against v7, the fallback), just not a PREVIEW one.
    await expect(page.locator(".preview-banner")).toHaveCount(0);
  });
});

// fix round 2, item 5: two invariants the shell/places specs already prove for index.html, ported
// here because report.html re-implements the SAME access gate (its inline early-fetch script is a
// verbatim second copy of index.html's, per this file's own header) and reads the SAME `#pl=` hash
// codec (src/lib/state/codec.ts) -- neither guarantee is specific to the map/places UI, so nothing
// here should assume report.html gets them for free.
test.describe("two invariants ported from shell.smoke.spec.ts / places.spec.ts", () => {
  // ported from shell.smoke.spec.ts's "public host + ?ver=v9: not one request under /v9/, falls
  // through to latest" -- same D6 gate, same fallback rule, exercised against report.html instead
  // of index.html. Fault: point `dataBase()` (or this file's own copy of it) at `/v9/`
  // unconditionally and `urls.filter(...)` is no longer empty -- red.
  test("public host + ?ver=v9: not one request under /v9/, falls through to latest", async ({
    page,
  }) => {
    const urls = collectRequests(page);
    await blockWasm(page);
    await routeBucket(page, "v7", BOOT_V7); // latest.txt = v7, a public release
    await routeSession(page, null); // no session.json -- this is the public host
    await routeSealFixture(page);

    await page.goto(`/report.html?ver=v9#pl=${PL}`);
    // two `.progress-line` paragraphs render here: the top status line ("Done -- N places.") AND
    // the denied-version note ("v9 is not available..."), both matching this class -- `.first()` is
    // the status line, source order.
    await expect(page.locator(".progress-line").first()).toContainText("Done");

    expect(urls.filter((u) => u.includes("/v9/"))).toEqual([]);
    expect(urls).toContain(`${BUCKET}v7/manifest.json`);
    await expect(page.locator(".preview-banner")).toHaveCount(0);
  });

  // ported from places.spec.ts's "the hash is absent from every request the browser makes during
  // the whole flow" -- report.html's place token lives in the same `#pl=` hash (parseSel), and a
  // browser never sends the fragment in a request by spec; the second-order check is that no URL
  // this app itself built (a fetch, an analytics payload logged as a request) carries the literal
  // token either. Fault: a request built from `location.hash` (or `sel.pl` reattached to a URL)
  // would carry the token and the loop below goes red.
  test("the hash (place token) is absent from every request the browser makes", async ({
    page,
  }) => {
    const urls = collectRequests(page);
    await gotoReport(page, { ver: "v9", preview: true });
    await expect(page.locator(".progress-line")).toContainText("Done");

    const hash = await page.evaluate(() => location.hash.replace(/^#pl=/, ""));
    expect(hash.length).toBeGreaterThan(0);
    for (const url of urls) {
      expect(url).not.toContain(hash);
    }
  });
});

test.describe("exports", () => {
  test("Download HTML produces a self-contained file", async ({ page }) => {
    await gotoReport(page, { ver: "v9", preview: true });
    const [download] = await Promise.all([
      page.waitForEvent("download"),
      page.getByRole("button", { name: "Download HTML" }).click(),
    ]);
    expect(download.suggestedFilename()).toMatch(/^PREVIEW_MarineSensitivity_.*\.html$/);
  });

  test("Print stylesheet: the watermark is visible only under print media", async ({ page }) => {
    await gotoReport(page, { ver: "v9", preview: true });
    await expect(page.locator(".print-watermark")).not.toBeVisible();
    await page.emulateMedia({ media: "print" });
    await expect(page.locator(".print-watermark")).toBeVisible();
    await expect(page.locator(".export-bar")).toBeHidden();
  });

  // fix round 1, item 2d: the downloaded HTML opens with the network cut off entirely and still
  // shows map, flowers and tables -- proves the export is genuinely self-contained, not merely
  // "worked while the same tab's cache was warm".
  test("Download HTML opens OFFLINE (context.offline) and shows map, flowers and tables", async ({
    page,
    browser,
  }) => {
    await gotoReport(page, { ver: "v9", preview: true });
    await expect(page.locator(".progress-line")).toContainText("Done");
    // let the map's own PNG capture (idle + two animation frames) land before downloading, or the
    // exported document's .map-print would still show "Map rendering...".
    await expect(page.locator(".map-print img")).toBeVisible({ timeout: 15_000 });

    const [download] = await Promise.all([
      page.waitForEvent("download"),
      page.getByRole("button", { name: "Download HTML" }).click(),
    ]);
    // `download.path()` is Playwright's OWN internal artifact path, with no `.html` extension --
    // opened directly via `file://`, Chromium cannot infer the MIME type and renders it as plain
    // text (measured: a literal `<pre>&lt;!doctype html&gt;...`). `saveAs()` to a real `.html`
    // path is what a person's browser download would actually give the file, and what makes
    // `file://` navigation treat it as HTML.
    const savedPath = test.info().outputPath("downloaded-report.html");
    await download.saveAs(savedPath);

    // `context({offline:true})` also blocks the file:// navigation itself on some platforms
    // (measured) -- the actual property under test is "makes zero http(s) requests", which is
    // asserted directly by routing every http(s) URL to a hard abort instead.
    const offlineContext = await browser.newContext();
    try {
      const offlinePage = await offlineContext.newPage();
      const networkRequests: string[] = [];
      await offlinePage.route(/^https?:\/\//, (route) => {
        networkRequests.push(route.request().url());
        return route.abort();
      });
      const errors: string[] = [];
      offlinePage.on("console", (m) => m.type() === "error" && errors.push(m.text()));
      await offlinePage.goto(`file://${savedPath}`);
      await expect(offlinePage.locator("figure.flower-panel")).toHaveCount(2);
      await expect(offlinePage.locator(".map-print img")).toBeVisible();
      await expect(
        offlinePage.locator("table", { hasText: "Mean component and overall scores" }),
      ).toBeVisible();
      expect(networkRequests).toEqual([]);
      // a self-contained document ships no <script> at all, so there is nothing to error --
      // any console error here would mean it tried (and failed) to reach the network.
      expect(errors).toEqual([]);
    } finally {
      await offlineContext.close();
    }
  });
});

test.describe("accessibility", () => {
  test("axe: zero serious/critical findings", async ({ page }) => {
    await gotoReport(page, { ver: "v9", preview: true });
    await expect(page.locator(".progress-line")).toContainText("Done");
    const { violations } = await new AxeBuilder({ page }).analyze();
    const bad = violations.filter((v) => v.impact === "serious" || v.impact === "critical");
    expect(bad).toEqual([]);
  });

  test("headings are hierarchical (one h1, every section a h2)", async ({ page }) => {
    await gotoReport(page, { ver: "v9", preview: true });
    await expect(page.locator("h1")).toHaveCount(1);
    const h2Texts = await page.locator("h2").allTextContents();
    expect(h2Texts.some((t) => t.includes("Introduction"))).toBe(true);
    expect(h2Texts.some((t) => t.includes("Table of Scores"))).toBe(true);
    expect(h2Texts.some((t) => t.includes("Summary of Species"))).toBe(true);
  });
});

// =====================================================================================
// fix round 1, item 2: real Parquet fixtures (e2e/fixtures/report/*, generate.sql) -- the
// species path AND a custom (drawn) place, with a REAL DuckDB-WASM boot (no blockWasm here).
// =====================================================================================
const REPORT_FIXTURES = new URL("./fixtures/report/", import.meta.url);
function readReportFixture(name: string): Buffer {
  return readFileSync(fileURLToPath(new URL(name, REPORT_FIXTURES)));
}
const CELL_TILES = [0, 1, 2, 3].map((t) => readReportFixture(`cell_tile${t}.parquet`));
const CELL_MODEL_TILES = [0, 1, 2, 3].map((t) => readReportFixture(`cell_model_tile${t}.parquet`));
const ENGINE_TAXON = readReportFixture("taxon.parquet");
const ENGINE_ZONE_TAXON = readReportFixture("zone_taxon.parquet");
const ENGINE_TAXONOMY = readReportFixture("taxonomy.parquet");

const ENGINE_VER = "v7"; // public per hermetic.ts's VERSIONS_FIXTURE -- no preview session needed

/** a 48x48 grid, tile.size=24 -> FOUR cell/cell_model partitions (see generate.sql's header). 20
 * zone keys (GAA/ALA carry real zone_taxon rows; Z3..Z20 do not, and render "No species found" --
 * the timing gate is about the WHOLE document completing, not every zone having rich data). */
const ENGINE_BOOT = {
  ver: ENGINE_VER,
  built_at: "2026-09-05T00:00:00Z",
  id_field: "mdl_seq", // v7 branch (sql/cell_model_seq.sql) -- no tables/model.parquet needed
  grid: {
    grid_id: "test05r",
    nc: 48,
    nr: 48,
    xmin: -125,
    ymax: 42,
    resx: 0.05,
    resy: 0.05,
    lon360: false,
    tile: { size: 24 },
  },
  release: { status: "release", access: "public" },
  // componentMetricKeys() (analysis/queries.ts) reads THIS for a custom place's scores_for_cells()
  // -- without it, computeScoreResults() skips the query entirely and Overall stays null (measured:
  // the first version of this fixture omitted `layers` and every custom-place score was "—").
  layers: [
    {
      metric_key: "extrisk_bird_ecoregion_rescaled",
      label: "Bird",
      category: "component",
      order: 1,
    },
    {
      metric_key: "extrisk_fish_ecoregion_rescaled",
      label: "Fish",
      category: "component",
      order: 2,
    },
  ],
  zones: {
    programarea: [
      { key: "GAA", name: "Gulf of America", n_cells: 100, area_km2: 1000, metrics: {} },
      { key: "ALA", name: "Alaska", n_cells: 100, area_km2: 1000, metrics: {} },
      ...Array.from({ length: 18 }, (_, i) => ({
        key: `Z${i + 3}`,
        name: `Zone ${i + 3}`,
        n_cells: 10,
        area_km2: 100,
        metrics: {},
      })),
    ],
  },
  datasets: [],
  palettes: { spectral_r: BOOT_V9.palettes.spectral_r },
};

async function routeEngineFixtures(page: Page, ver: string) {
  const files: Record<string, Buffer> = {
    [`${ver}/app/taxon.parquet`]: ENGINE_TAXON,
    [`${ver}/app/zone_taxon.parquet`]: ENGINE_ZONE_TAXON,
    [`${ver}/app/taxonomy.parquet`]: ENGINE_TAXONOMY,
  };
  for (let t = 0; t < 4; t++) {
    files[`${ver}/app/cell/tile=${t}/data_0.parquet`] = CELL_TILES[t];
    files[`${ver}/serve/cell_model/tile=${t}/data_0.parquet`] = CELL_MODEL_TILES[t];
  }
  await page.route(
    (url) =>
      url.href.startsWith(BUCKET) && (url.href.includes("/app/") || url.href.includes("/serve/")),
    (route) => {
      const path = route.request().url().slice(BUCKET.length);
      const body = files[path];
      if (!body) return route.fallback();
      return route.fulfill({ status: 200, contentType: "application/octet-stream", body });
    },
  );
}

// the drawn rectangle -124.5,40.0 to -123.0,41.5 -- astride BOTH the grid's lon boundary (-123.8)
// and lat boundary (40.8), so it touches all four cell_model tiles (generate.sql's own header).
const CUSTOM_PLACE: Place = {
  kind: "geom",
  name: "TestPlace",
  geometry: {
    type: "Polygon",
    coordinates: [
      [
        [-124.5, 40.0],
        [-123.0, 40.0],
        [-123.0, 41.5],
        [-124.5, 41.5],
        [-124.5, 40.0],
      ],
    ],
  },
};
const CUSTOM_TOKEN = encodePlace(CUSTOM_PLACE);

/**
 * How long an ENGINE-backed report (real DuckDB-WASM boot + Parquet scan) gets to reach "Done"
 * in a test whose subject is NOT performance.
 *
 * 0.10.14: the two waits in "the permalink reproduces byte-identical scores.csv/species.csv"
 * carried no timeout at all, i.e. Playwright's 5 s per-assertion default — a machine-speed
 * assumption that held on a laptop and not on ubuntu-latest (run 35819393922: both webkit
 * attempts still read "Scoring TestPlace (1 of 1)…" at 5 s). The measured budget for exactly this
 * place, cold, is the sibling gate 30 lines up: "a custom (drawn) 4-tile place: scores AND species
 * render, cold, in < 15 s", which PASSED on webkit/linux in that same run. This test does that
 * work TWICE — once in `page`, then again in a second, fresh context whose HTTP cache is empty
 * while the first page is still alive (two DuckDB-WASM instances on a 2-core runner) — so it gets
 * 2× that measured 15 s. Nothing here is a performance claim: the 15 s cold-load budget and
 * species.timing.spec.ts are the gates that make one, and neither is relaxed.
 */
const ENGINE_DONE_TIMEOUT_MS = 30_000;

async function gotoEngineReport(page: Page, pl: string) {
  await routeBucket(page, ENGINE_VER, ENGINE_BOOT);
  await routeEngineFixtures(page, ENGINE_VER);
  await routeSession(page, null);
  await routeSealFixture(page);
  await page.goto(`/report.html?ver=${ENGINE_VER}#pl=${pl}`);
}

test.describe("engine-backed paths (real DuckDB-WASM, real Parquet fixtures, fix round 1 item 2)", () => {
  test("a custom (drawn) 4-tile place: scores AND species render, cold, in < 15 s", async ({
    page,
  }) => {
    const start = Date.now();
    await gotoEngineReport(page, CUSTOM_TOKEN);
    await expect(page.locator(".progress-line")).toContainText("Done", { timeout: 15_000 });
    expect(Date.now() - start).toBeLessThan(15_000);

    // scores: every cell in the drawn box carries bird=50/fish=30 -> Overall 40.
    const table = page.locator("table", { hasText: "Mean component and overall scores" });
    await expect(table.locator("tr", { hasText: "TestPlace" })).toContainText("40");

    // species: real rows combined across all four cell_model tiles (not "No species found").
    await expect(page.getByText("No species found for this area.")).toHaveCount(0);
    await expect(page.getByText("Marbled Murrelet").first()).toBeVisible();
    await expect(page.getByText("Pacific Herring").first()).toBeVisible();
    await expect(page.getByText("Ashy Storm-Petrel").first()).toBeVisible();
  });

  test("20 zone places render completely in < 10 s", async ({ page }) => {
    const keys = ENGINE_BOOT.zones.programarea.map((z) => z.key);
    expect(keys).toHaveLength(20);
    const pl = encodePlace({ kind: "zone", set: "pa", keys });
    const start = Date.now();
    await gotoEngineReport(page, pl);
    await expect(page.locator(".progress-line")).toContainText("Done", { timeout: 10_000 });
    expect(Date.now() - start).toBeLessThan(10_000);
    await expect(page.locator("figure.flower-panel")).toHaveCount(20);
  });

  test("the permalink reproduces byte-identical scores.csv/species.csv in a FRESH context", async ({
    page,
    browser,
  }) => {
    async function downloadZipEntries(p: Page) {
      const [download] = await Promise.all([
        p.waitForEvent("download"),
        p.getByRole("button", { name: "Data package (ZIP)" }).click(),
      ]);
      const path = await download.path();
      const buf = readFileSync(path!);
      return unzipSync(new Uint8Array(buf));
    }

    await gotoEngineReport(page, CUSTOM_TOKEN);
    await expect(page.locator(".progress-line")).toContainText("Done", {
      timeout: ENGINE_DONE_TIMEOUT_MS,
    });
    const first = await downloadZipEntries(page);

    const freshContext = await browser.newContext();
    try {
      const freshPage = await freshContext.newPage();
      await gotoEngineReport(freshPage, CUSTOM_TOKEN);
      await expect(freshPage.locator(".progress-line")).toContainText("Done", {
        timeout: ENGINE_DONE_TIMEOUT_MS,
      });
      const second = await downloadZipEntries(freshPage);

      const scoresName = Object.keys(first).find((k) => k.startsWith("scores_"));
      const speciesName = Object.keys(first).find((k) => k.startsWith("species_"));
      expect(scoresName).toBeDefined();
      expect(speciesName).toBeDefined();
      expect(Buffer.from(second[scoresName!])).toEqual(Buffer.from(first[scoresName!]));
      expect(Buffer.from(second[speciesName!])).toEqual(Buffer.from(first[speciesName!]));
    } finally {
      await freshContext.close();
    }
  });
});

// =====================================================================================
// fix round 1, item 2c: Chromium page.pdf() -> pdf-parse. Uses the blockWasm zone fixtures
// (BOOT_V9/BOOT_V7): place labels and table row labels are the place NAMES, which need no
// engine; the map PNG and the watermark are print-layer concerns, also engine-independent.
// =====================================================================================

/** the watermark is CSS-rotated (`transform: rotate(-30deg)`), so pdfjs/pdf-parse extracts each
 * glyph as its own positioned run with a newline between -- "PREVIEW" comes back as "P\nR\nE\n...".
 * This strips ALL whitespace before matching it, which is safe ONLY for this one all-caps,
 * no-internal-space word (unlike "Gulf of America", never run through this). */
function containsWatermark(text: string): boolean {
  return text.replace(/\s+/g, "").includes("PREVIEW");
}

test.describe("page.pdf() (chromium): labels, table headers, watermark, map image", () => {
  // page.pdf() exists only in headless Chromium ("PDF generation is only supported for Headless
  // Chromium"): on webkit/firefox these are skipped, not failed. The other engines still run the
  // document, exports and round-trip specs above.
  test.skip(({ browserName }) => browserName !== "chromium", "page.pdf() is Chromium-only");
  test("v9 preview: place/table labels present, PREVIEW watermark present, map image not blank", async ({
    page,
  }) => {
    await gotoReport(page, { ver: "v9", preview: true });
    await expect(page.locator(".progress-line")).toContainText("Done");
    await expect(page.locator(".map-print img")).toBeVisible({ timeout: 15_000 });

    const pdfBuffer = await page.pdf({ printBackground: true, format: "Letter" });
    const { text } = await pdfParse(pdfBuffer);

    // every place label and table row label (report pipeline spec §7's own wording).
    expect(text).toContain("Gulf of America");
    expect(text).toContain("Alaska");
    // the LAST column header ("Overall") present -- the proxy this suite uses for "no table
    // clipped" (report.css's break-inside: avoid is the source-level half of that gate, see
    // tests/report/printBreakInside.test.ts; true per-page clipping needs a PDF layout
    // inspector this suite does not build -- disclosed, not hidden).
    expect(text).toContain("Overall");
    // the watermark text, present for a restricted release on a preview session.
    expect(containsWatermark(text)).toBe(true);
  });

  test("v7 public: the PREVIEW watermark text is ABSENT", async ({ page }) => {
    await gotoReport(page, { ver: "v7", preview: false });
    await expect(page.locator(".progress-line")).toContainText("Done");

    const pdfBuffer = await page.pdf({ printBackground: true, format: "Letter" });
    const { text } = await pdfParse(pdfBuffer);
    expect(text).toContain("Gulf of America");
    expect(containsWatermark(text)).toBe(false);
  });

  // fix round 2, item 3: the running footer used to be TWO footers (a static `@bottom-center`
  // placeholder plus a position:fixed `.print-footer` carrying the real permalink/release text) --
  // no page number anywhere, and on page 3 the fixed footer collided with body content. Now
  // `@bottom-center` is the ONLY footer, fed the real strings through CSS custom properties
  // (Report.svelte sets them), with `counter(page)`/`counter(pages)` for the page numbers -- drop
  // either `counter(page)` from report.css or the custom-property wiring from Report.svelte and
  // this goes red (no "page N of M" match / no permalink in the extracted text).
  test("the running footer: real permalink + release + page N of M on every page, no overprinted/dropped body text", async ({
    page,
  }) => {
    await gotoReport(page, { ver: "v9", preview: true });
    await expect(page.locator(".progress-line")).toContainText("Done");
    await expect(page.locator(".map-print img")).toBeVisible({ timeout: 15_000 });

    const permalinkHref = await page.locator(".report-header a").getAttribute("href");
    expect(permalinkHref).toBeTruthy();

    const pdfBuffer = await page.pdf({ printBackground: true, format: "Letter" });
    const { text, numpages } = await pdfParse(pdfBuffer);
    // 0.10.14: `pdf-parse` joins RENDERED LINES with `\n`, so every prose assertion below runs
    // against the whitespace-normalized text (see e2e/pdfText.ts) -- otherwise the assertion is
    // really about where the runner's fonts happened to wrap the paragraph. Attached either way,
    // so a future red on another platform shows the text instead of a truncated diff.
    const flat = normalizePdfText(text);
    await test.info().attach("pdf-text-normalized.txt", { body: flat, contentType: "text/plain" });

    expect(numpages).toBeGreaterThan(1); // a single-page PDF can't prove "on every page"
    expect(flat).toMatch(/page 1 of \d+/); // counter(page)/counter(pages) -- no JS page-counting
    expect(flat).toContain(permalinkHref);
    // the ONE footer now, never the old fixed-position second copy.
    expect(flat).not.toContain("MarineSensitivity Atlas — printed report");

    // the Sources section's own last sentence, intact -- exactly what a page-3 overprint used to
    // corrupt/drop (model.ts's SOURCES_TEXT, static and known). The WHOLE sentence, not just its
    // tail: a line-break-proof assertion must not also become a shorter one.
    expect(flat).toContain(
      "Species rows are every distribution model whose range overlaps the area, weighted by " +
        "modelled habitat suitability, the governing extinction-risk score and the overlapping " +
        "area.",
    );
  });
});
