-- cell_components.sql  --  one clicked cell, its component scores and its cell facts
--
-- R twin: msens::scores_for_cells(con, tibble(cell_id, pct_covered = 100)) (msens/R/calc.R:286-334)
--   degenerates to exactly this for a single cell -- with one cell at pct 100 the blend is
--   sum(v * 100) / 100 = v -- plus the `cell` row itself (app_bundle.R:866-880's wide tile).
--   .component_of() is calc.R:224-228.
-- Pinned by: tests/fixtures/parity/{v7,v9}/cell_components_*.json, which is generated by that
--   single-cell scores_for_cells() call, so the degeneration is asserted, not assumed.
--
-- WHY A SEPARATE FILE rather than running sql/scores_for_cells.sql with a one-row place. Because
-- the click popup asks a different question: it wants the cell's OWN values (`area_km2`, `in_usa`,
-- `in_pra`) beside the components, it must answer for a cell OUTSIDE the study area too (the popup
-- says "outside US waters", it does not go blank), and it must never depend on a `place_cell` table
-- that a click has no reason to build. `in_usa` is returned RAW here -- NULL on v1-v7, which have no
-- such column (sql/cells_in_study_area.sql's header) -- so the caller can say "not recorded" rather
-- than inventing a FALSE.
--
-- Numbers never come from the tile server (master-plan D4): a clicked cell's score is read from the
-- wide Parquet tile, never by sampling a rendered COG pixel.
--
-- `cols` is the ident()-validated component column list (sql.ts's RAW_ALLOWLIST); a cell_id that is
-- not in any loaded tile returns zero rows, which is a real answer (off-grid or unscored), not an
-- error.
WITH c AS (
  SELECT cell_id, area_km2, in_usa, in_pra, {{cols}}
    FROM cell
   WHERE cell_id = {{cell_id}}
),
long AS (
  UNPIVOT c
     ON {{cols}}
   INTO NAME metric_key VALUE v
)
SELECT long.metric_key,
       long.v                                 AS val,
       regexp_replace(
         regexp_replace(
           regexp_replace(long.metric_key, 'extrisk_', ''),
           '_ecoregion_rescaled', ''),
         '_', ' ')                            AS component,
       c.area_km2,
       c.in_usa,
       c.in_pra
  FROM long
 CROSS JOIN c
 WHERE regexp_matches(long.metric_key, {{metric_pattern}})
   AND regexp_replace(
         regexp_replace(
           regexp_replace(long.metric_key, 'extrisk_', ''),
           '_ecoregion_rescaled', ''),
         '_', ' ') <> 'all'
 ORDER BY long.metric_key
