-- atlas-2 Step 3 (Sonnet half): the ONE trivial SQL template this half of the step ships -- NOT a
-- twin of any msens function. It exists only to prove curly-brace placeholder substitution, lit()
-- escaping and the fixed RAW allow-list end to end against a real DuckDB-WASM connection (see
-- tests/fixtures/engine-e2e). {{from}} is an app-built RAW fragment (normally a TableStore ref's
-- `.from`, e.g. read_parquet('taxon')); {{probe}} is an ordinary lit()'d value round-tripped as a
-- column -- the injection-safety gate feeds an injection string through this exact slot and asserts
-- it comes back as inert data, never as a second statement.
--
-- The real SQL twins -- species_for_zone.sql, species_for_cells.sql, scores_for_cells.sql,
-- cell_components.sql, composition.sql -- are the Opus half of this step, once the R side lands.
SELECT count(*) AS n, {{probe}} AS probe FROM {{from}}
